<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "frp_form_answers"
 *
 * Auto generated by Extension Builder 2017-05-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Forms Export',
    'description' => 'Adds the possibility, as a finisher, to save and export the form entries from customers',
    'category' => 'module',
    'author' => '!frappant',
    'author_email' => 'support@frappant.ch',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '4.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '12.0.0-12.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
