# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Frappant\FrpFormAnswers\:
    resource: '../Classes/*'

  Frappant\FrpFormAnswers\Utility\FormAnswersUtility:
    public: true

  Frappant\FrpFormAnswers\Controller\FormEntryController:
    tags: ['backend.controller']

  Frappant\FrpFormAnswers\EventListener\UploadPathEnrichmentEventListener:
    tags:
      - name: event.listener
        identifier: 'frp-form-answers.upload-path-enrichment'
        event: Frappant\FrpFormAnswers\Event\ManipulateFormValuesEvent
        priority: 0
